const carsData = [
	{
		id: 1,
		marka: 'Toyota',
		model: 'Corolla',
		rocznik: 2020,
		przebieg: 200000,
		paliwo: 'Diesel',
		pojemnosc: '1600',
		alt: 'First Image',
		src: '/images/about-us.jpg',
	},
	{
		id: 2,
		marka: 'Toyotaa',
		model: 'Corolla',
		rocznik: 2020,
		przebieg: 200000,
		paliwo: 'Diesel',
		pojemnosc: '1600',
		alt: 'First Image',
		src: '/images/about-us.jpg',
	},
	{
		id: 3,
		marka: 'Seat',
		model: 'Leon',
		rocznik: 2019,
		przebieg: 100000,
		paliwo: 'Diesel',
		pojemnosc: '2000',
		alt: 'First Image',
		src: '/images/about-us.jpg',
	},
	{
		id: 4,
		marka: 'Seat',
		model: 'Leon',
		rocznik: 2019,
		przebieg: 100000,
		paliwo: 'Diesel',
		pojemnosc: '2000',
		alt: 'First Image',
		src: '/images/about-us.jpg',
	},
	{
		id: 4,
		marka: 'Seat',
		model: 'Leon',
		rocznik: 2019,
		przebieg: 100000,
		paliwo: 'Diesel',
		pojemnosc: '2000',
		alt: 'First Image',
		src: '/images/about-us.jpg',
	},
]

export default carsData
